function buildRay(){
	
	MAXKMERLENGTH=$1

	mpicxx ../code/SeedExtender/Direction.cpp ../code/SequencesIndexer/ReadAnnotation.cpp \
../code/SeedingData/GraphPath.cpp \
../RayPlatform/*/*.cpp  ../code/VerticesExtractor/Vertex.cpp test_kmer.cpp  ../code/Mock/common_functions.cpp  \
../code/KmerAcademyBuilder/Kmer.cpp -I$CODE -I. -D MAXKMERLENGTH=$MAXKMERLENGTH -DASSERT -I../code -I .. -I ../RayPlatform

}

buildRay 32
./a.out \
TGAAATGGAAATGGTCTGGGAAG

buildRay 64
./a.out \
TGAAATGGAAATGGTCTGGGAAAAACAACTAAAAGATATTATTGTAGTA

buildRay 96
./a.out \
TGAAATGGAAATGGTCTGGGAAAAACAACTAAAAGATATTATTGTAGTAGCTGGTTTTGAAATTTATGACGCTGAAATAACTCCCCACTA

buildRay 128
./a.out \
TGAAATGGAAATGGTCTGGGAAAAACAACTAAAAGATATTATTGTAGTAGCTGGTTTTGAAATTTATGACGCTGAAATAACTCCCCACTATATTTTCACCAAATTTATT

buildRay 75
./a.out \
TGAAATGGAAATGGTCTGGGAAAAACAACTAAAAGATATTATTGTAGTAGCTGGTTTTGAAATTTATGACGCT

buildRay 50
./a.out \
TGAAATGGAAATGGTCTGGGAAAAACAACTAAAAGATATTAT
