#!/usr/bin/env python

import sys

for line in sys.stdin:
	tokens=line.split("\t")

	if len(tokens)<14:
		continue

	name1=tokens[9]
	name2=tokens[13]

	if name1==name2:
		continue

	print(line.strip())
